echo "aws resourcegroupstaggingapi get-resources --region us-east-2 $(aws resourcegroupstaggingapi get-resources --region us-east-2)"
echo "aws resourcegroupstaggingapi get-resources --region us-east-1 $(aws resourcegroupstaggingapi get-resources --region us-east-1)"
echo "aws resourcegroupstaggingapi get-resources --region us-west-1 $(aws resourcegroupstaggingapi get-resources --region us-west-1)"
echo "aws resourcegroupstaggingapi get-resources --region us-west-2 $(aws resourcegroupstaggingapi get-resources --region us-west-2)"
echo "aws resourcegroupstaggingapi get-resources --region af-south-1 $(aws resourcegroupstaggingapi get-resources --region af-south-1)"
echo "aws resourcegroupstaggingapi get-resources --region ap-east-1 $(aws resourcegroupstaggingapi get-resources --region ap-east-1)"
echo "aws resourcegroupstaggingapi get-resources --region ap-south-1 $(aws resourcegroupstaggingapi get-resources --region ap-south-1)"
echo "aws resourcegroupstaggingapi get-resources --region ap-northeast-3 $(aws resourcegroupstaggingapi get-resources --region ap-northeast-3)"
echo "aws resourcegroupstaggingapi get-resources --region ap-northeast-2 $(aws resourcegroupstaggingapi get-resources --region ap-northeast-2)"
echo "aws resourcegroupstaggingapi get-resources --region ap-southeast-1 $(aws resourcegroupstaggingapi get-resources --region ap-southeast-1)"
echo "aws resourcegroupstaggingapi get-resources --region ap-southeast-2 $(aws resourcegroupstaggingapi get-resources --region ap-southeast-2)"
echo "aws resourcegroupstaggingapi get-resources --region ap-northeast-1 $(aws resourcegroupstaggingapi get-resources --region ap-northeast-1)"
echo "aws resourcegroupstaggingapi get-resources --region ca-central-1 $(aws resourcegroupstaggingapi get-resources --region ca-central-1)"
echo "aws resourcegroupstaggingapi get-resources --region eu-central-1 $(aws resourcegroupstaggingapi get-resources --region eu-central-1)"
echo "aws resourcegroupstaggingapi get-resources --region eu-west-1 $(aws resourcegroupstaggingapi get-resources --region eu-west-1)"
echo "aws resourcegroupstaggingapi get-resources --region eu-west-2 $(aws resourcegroupstaggingapi get-resources --region eu-west-2)"
echo "aws resourcegroupstaggingapi get-resources --region eu-south-1 $(aws resourcegroupstaggingapi get-resources --region eu-south-1)"
echo "aws resourcegroupstaggingapi get-resources --region eu-west-3 $(aws resourcegroupstaggingapi get-resources --region eu-west-3)"
echo "aws resourcegroupstaggingapi get-resources --region eu-north-1 $(aws resourcegroupstaggingapi get-resources --region eu-north-1)"
echo "aws resourcegroupstaggingapi get-resources --region me-south-1 $(aws resourcegroupstaggingapi get-resources --region me-south-1)"
echo "aws resourcegroupstaggingapi get-resources --region sa-east-1 $(aws resourcegroupstaggingapi get-resources --region sa-east-1)"
# commands to build:
# cat ~/Documents/regions.txt | command xargs -I {} echo "echo \"aws resourcegroupstaggingapi get-resources --region {}\$(aws resourcegroupstaggingapi get-resources --region {})\"" > regions.sh
# now cleanup files using vim files: `:%s/ctrl-v + ctrl m/ /; :%s/ctrl-v + ctrl m//;`
